server:
  port: 8189

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tgfirstbot
    username: userok
    password: p@ssw0rd
  jpa:
    generate-ddl: true

salt: jNcDYAkXOqesX0aLAzSH5SffNWuO8m